# generated by datamodel-codegen:
#   filename:  message.json
#   timestamp: 2022-06-14T15:04:14+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    lat: float
    long: float
    device_id: str
    temperature: float
    humidity: float
    pm2_5: float
    pm10: float
    timestamp: int


print(Model.schema_json(indent=2))
